"Cart.MD5" "@@MD5@@"
"Cart.Manufacturer" "Bruce-Robert Pocock"
"Cart.ModelNo" "Griz0.PlusROM.@@TV@@"
"Cart.Name" "Grizzards PlusROM Edition"
"Cart.Rarity" "Homebrew"
"Cart.Type" "EF"
"Cart.Url" "https://star-hope.org/games/Grizzards"
"Controller.Left" "GENESIS"
"Controller.Right" "JOYSTICK"
"Display.Format" "@@TV@@"
"Display.Phosphor" "YES"
