"Cart.MD5" "@@MD5@@"
"Cart.Manufacturer" "Bruce-Robert Pocock"
"Cart.ModelNo" "Griz0.Demo.@@TV@@"
"Cart.Name" "Grizzards Demo"
"Cart.Rarity" "Homebrew"
"Cart.Type" "F4"
"Controller.Left" "JOYSTICK"
"Controller.Right" "ATARIVOX"
"Display.Format" "@@TV@@"
"Display.Phosphor" "YES"
