"Cart.MD5" "@@MD5@@"
"Cart.Manufacturer" "AtariAge"
"Cart.ModelNo" "Griz@@ATARIAGESAVE@@.@@TV@@"
"Cart.Name" "Grizzards"
"Cart.Rarity" "Homebrew (Interworldly+AtariAge)"
"Cart.Type" "EFF"
"Cart.Url" "https://Grizzards.com/"
"Controller.Left" "JOY2B+"
"Controller.Right" "ATARIVOX"
"Display.Format" "@@TV@@"
"Display.Phosphor" "YES"
