"Cart.MD5" "f594ebb4c904fb53a58749cc3baf029c"
"Cart.Manufacturer" "Bruce-Robert Pocock"
"Cart.ModelNo" "Griz0.@@TV@@"
"Cart.Name" "Grizzards"
"Cart.Rarity" "Homebrew"
"Cart.Type" "F4"
"Controller.Left" "JOYSTICK"
"Controller.Right" "ATARIVOX"
"Display.Format" "@@TV@@"
"Display.Phosphor" "YES"
