"Cart.MD5" "@@MD5@@"
"Cart.Manufacturer" "Bruce-Robert Pocock"
"Cart.ModelNo" "Griz0.Demo.@@TV@@"
"Cart.Name" "Grizzards Demo"
"Cart.Rarity" "Homebrew (AtariAge)"
"Cart.Type" "F4"
"Cart.Url" "https://Grizzards.com/"
"Controller.Left" "JOY2B+"
"Controller.Right" "ATARIVOX"
"Display.Format" "@@TV@@"
"Display.Phosphor" "YES"
