"Cart.MD5" "@@MD5@@"
"Cart.Manufacturer" "Bruce-Robert Pocock"
"Cart.ModelNo" "Griz0.NoSave.@@TV@@"
"Cart.Name" "Grizzards No-Save Demo"
"Cart.Rarity" "Homebrew (AtariAge)"
"Cart.Type" "F4"
"Cart.Url" "https://Grizzards.com/"
"Controller.Left" "JOY2B+"
"Controller.Right" "JOYSTICK"
"Display.Format" "@@TV@@"
"Display.Phosphor" "YES"
